### ISSUE TITLE
type of the length property

### ISSUE THREAD

**Issue by emanuelapitassi** [MasterOfWebM/WebM-Converter#3]
Hi, 
thanks for this tool.
Anyway, I don't understand what is the expected type of the Length field.
Let suppose that the video I want to convert to webm is of 10 minutes and 24 seconds, I am not able to insert this time duration due to the maximum of three characters possible to insert. 
Maybe do I misunderstand this field?
What is the correct type for this field? 
thank you in advance.

**Comment by MasterOfWebM** [comment]
The _length_ field is designed to take the amount of seconds to encode. So if you want to make something 10 minutes and 24 seconds, you would enter **624**.

**Comment by MasterOfWebM** [comment]
Feel free to reopen the issue if I did not fix the issue.

Thank you.
